In [67]:
import torch 
import torch.nn as nn 
import torch.optim as optim 

class Model(nn.Module):
    def __init__(self, input_size, output_size):
        super(Model, self).__init__()
        self.input_size = input_size
        self.output_size = output_size
        self.fc = nn.Linear(in_features=input_size, out_features=output_size)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.fc(x)
        x = self.relu(x)



In [68]:
input_size = 50
output_size = 5
def burnin_scheduler(epoch):
    if epoch < 10:
        return 1
    elif epoch < 20:
        return 0.5
    else:
        return 0.1
    

model = Model(input_size, output_size)
optimizer = optim.SGD(params=model.parameters(), lr=0.01)
scheduler = optim.lr_scheduler.LambdaLR(optimizer, burnin_scheduler, last_epoch=-1)

In [69]:
epoches = 30

for e in range(epoches):
    # print(scheduler.get_lr())
    print("epoch: %d : " % e, optimizer.param_groups[0]['lr'])
    scheduler.step()
    optimizer.step()

epoch: 0 :  0.01
epoch: 1 :  0.01
epoch: 2 :  0.01
epoch: 3 :  0.01
epoch: 4 :  0.01
epoch: 5 :  0.01
epoch: 6 :  0.01
epoch: 7 :  0.01
epoch: 8 :  0.01
epoch: 9 :  0.01
epoch: 10 :  0.005
epoch: 11 :  0.005
epoch: 12 :  0.005
epoch: 13 :  0.005
epoch: 14 :  0.005
epoch: 15 :  0.005
epoch: 16 :  0.005
epoch: 17 :  0.005
epoch: 18 :  0.005
epoch: 19 :  0.005
epoch: 20 :  0.001
epoch: 21 :  0.001
epoch: 22 :  0.001
epoch: 23 :  0.001
epoch: 24 :  0.001
epoch: 25 :  0.001
epoch: 26 :  0.001
epoch: 27 :  0.001
epoch: 28 :  0.001
epoch: 29 :  0.001


In [72]:
torch.__version__

'1.6.0'

In [6]:
import numpy as np 

a = [i for i in range(100)]
a = np.array(a)
a_2 = a[1:50:2]
print(a_2)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [2]:
import numpy as np 

filter = np.random.randn(1, 3, 3)
print(filter)

[[[ 1.51203448  1.46000085 -2.30476504]
  [ 1.30120436 -1.40447534  1.10973464]
  [-0.50198817 -0.87963181  0.88677353]]]


In [2]:
import numpy as np 
import torch 

a = np.array([3,5,7,9])
b = np.array([2,6,5,10])

a = torch.from_numpy(a)
b = torch.from_numpy(b)

print(a, b)
c = torch.min(a[:2], b[:2])
print(c)

tensor([3, 5, 7, 9]) tensor([ 2,  6,  5, 10])
tensor([2, 5])


In [47]:
a = np.array(range(10))
b = np.array(range(10))

x, y = np.meshgrid(a, b)
# print(x)
print(y)
x = np.repeat(x[:, :, np.newaxis], 3, axis=2).flatten()
print(x)

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9 0 0 0 1 1 1 2
 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9 0 0 0 1 1 1 2 2 2 3 3 3 4 4
 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9 0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6
 7 7 7 8 8 8 9 9 9 0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9
 9 9 0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9 0 0 0 1 1
 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9 0 0 0 1 1 1 2 2 2 3 3 3
 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9 0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6
 6 6 7 7 7 8 8 8 9 9 9 0 0 0 1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8
 8 9 9 9]


In [64]:
x = np.array([[0,2,1,3], [2,3,1,5], [3,2,0,1]])
# x_max = np.max(x[:2, :2])
print(x)
x_pad = np.pad(x, ((2,3),(0,0)), 'constant', constant_values=0)
print(len(x_pad.shape))
try:
    assert(x.shape == x_pad.shape)
except AssertionError:
    print("x shape is not the same as x_pad")

[[0 2 1 3]
 [2 3 1 5]
 [3 2 0 1]]
2
x shape is not the same as x_pad


In [51]:
m = nn.MaxPool2d(2, stride=2)
x = torch.randn(1, 1, 4, 4)
re = m(x)
print(re.shape)

torch.Size([1, 1, 2, 2])


In [8]:
import torch.nn as nn 
x = torch.tensor([1.2, 0.5, -0.9], dtype=torch.float)
y = torch.tensor([0, 1, 1], dtype=torch.float)

bce = nn.BCELoss()
bcelog = nn.BCEWithLogitsLoss()

loss_1 = bce(nn.Sigmoid()(x), y)
loss_2 = bcelog(x, y)

print(loss_1)
print(loss_2)

sig = nn.Sigmoid()(x)

log = -torch.log(sig)
log = torch.mean(log)
print(log)



tensor(0.6595)
tensor(0.6595)
tensor(0.6595)


In [9]:
class Focus(nn.Module):
    
    def __init__(self, c1, c2, k=1):
        super(Focus, self).__init__()
        self.conv = nn.Conv2d(c1*4, c2, k)

    def forward(self, x):
        return self.conv(torch.cat([x[..., ::2, ::2], x[..., ::2, 1::2], x[..., 1::2, ::2], x[..., 1::2, 1::2]], dim=1))


In [10]:
img = torch.randn(1, 3, 14, 14)
focus = Focus(3, 32)
new_img = focus(img)
print(new_img.shape)

torch.Size([1, 32, 7, 7])
