In [4]:
import numpy as np 

a = np.array([1,2,3]).astype(np.float32)
a = np.mean(a)
print(a)

2.0


In [7]:
def c_list(list):
    nlist = list.copy()
    nlist *= 2
    return nlist 

list = [2,3]
list = np.array(list)
clist = c_list(list)
print(list, clist)

[2 3] [4 6]


In [2]:
from pycocotools.coco import COCO

coco = COCO('/home/baodi/data/cocodataset/annotations/instances_val2017.json')

loading annotations into memory...
Done (t=1.12s)
creating index...
index created!


In [18]:
from pprint import pprint

imgids = coco.getImgIds()
imgid = imgids[5]
# print(imgid)
annids = coco.getAnnIds(imgIds=imgid)
anns = coco.loadAnns(annids)[0]
catid = anns['category_id']
cat_name = coco.loadCats(catid)
pprint(cat_name[0]['name'])

'toilet'


In [20]:
a = [1,2,3,4,5]
b = [0, 3]
c = [a[i] for i in b]
print(c)

[1, 4]


In [8]:
import torch 
from pprint import pprint

a = torch.tensor([1,2,3])
b = a.clone()
a[0] = 5
pprint(a)
pprint(b)

tensor([5, 2, 3])
tensor([1, 2, 3])


In [31]:
b1 = torch.tensor([[0,0,2,2], [0,0,4,4]]).to(torch.float)
b2 = torch.tensor([[0,0,2,2], [0,0,2,4], [1,1,4,4],[4,5,5,6]]).to(torch.float)

b1 = b1.view(b1.shape[0], 1, b1.shape[1])

# inter_boxes = torch.zeros((b1.shape[0], b2.shape[0]))
left = torch.max(b1[..., 0], b2[..., 0]).unsqueeze(2)
top = torch.max(b1[..., 1], b2[..., 1]).unsqueeze(2)
right = torch.min(b1[..., 2], b2[..., 2]).unsqueeze(2)
bottom = torch.min(b1[..., 3], b2[..., 3]).unsqueeze(2)
inter_boxes = torch.cat((left, top, right, bottom), dim=2)

inter_areas = (inter_boxes[..., 2] - inter_boxes[..., 0]).clamp(min=0) * (inter_boxes[..., 3] - inter_boxes[..., 1]).clamp(min=0)
# inter_areas = inter_areas.clamp(min=0)

b1_area = (b1[..., 2] - b1[..., 0]) * (b1[..., 3] - b1[..., 1])
b2_area = (b2[..., 2] - b2[..., 0]) * (b2[..., 3] - b2[..., 1])
union_areas = b1_area + b2_area - inter_areas

ious = inter_areas / union_areas
pprint(inter_areas)
pprint(union_areas)
pprint(ious)

# pprint(inter_boxes[1, 3, :])

tensor([[4., 4., 1., 0.],
        [4., 8., 9., 0.]])
tensor([[ 4.,  8., 12.,  5.],
        [16., 16., 16., 17.]])
tensor([[1.0000, 0.5000, 0.0833, 0.0000],
        [0.2500, 0.5000, 0.5625, 0.0000]])


In [42]:
a = torch.tensor(([4,2],[5,6],[2,3]))

_, ind = a[:, 0].sort(dim=0)
# torch.sort(descending=)
pprint(a[ind])
pprint(a[2:, :].shape)
pprint(a[:1, :].shape)

tensor([[2, 3],
        [4, 2],
        [5, 6]])
torch.Size([1, 2])
torch.Size([1, 2])


In [57]:
a = torch.tensor(5.65)
b = torch.tensor(4.82)
c = int(a-b)
print(c)
d = torch.tensor([1.2, 2.2, 3.4, 4.5])
e = torch.floor(d)
print(d)
print(e)

0
tensor([1.2000, 2.2000, 3.4000, 4.5000])
tensor([1., 2., 3., 4.])
