In [1]:
%matplotlib inline

In [24]:
import os

import torch 
from torch.utils.data.dataloader import DataLoader
from torch.utils.data.dataset import Dataset
import torchvision.transforms as transforms 

from pycocotools.coco import COCO

import numpy as np 
import cv2

from collections import OrderedDict
from pprint import pprint

In [25]:
s = "ababa=bbab"
sl = s.split('=')
print(sl)

['ababa', 'bbab']


In [91]:
import torch.nn as nn 

x = torch.tensor([0, 0], dtype=torch.float)
y = nn.Softmax()(x)
print(y)
print(torch.sum(y))

tensor([0.5000, 0.5000])
tensor(1.)


In [123]:
x=torch.randn((1, 18, 13, 13))
x[0, :, 0, 0]=torch.tensor(range(18), dtype=torch.float)
# pprint(x[0,:,0, 0])
B, C, H, W = x.shape
x = x.view(B, C, H*W)
x = x.transpose(1, 2).contiguous()
x = x.view(B, H*W*3, C//3)
# x = x.view(B, H*W*3, C//3).contiguous()

# pprint(x.shape)
# x = torch.tensor([0,1,2,3,4,5], dtype=torch.float)
# sig = nn.Sigmoid()
# pprint(sig(x))
pprint(x.shape)

torch.Size([1, 507, 6])


In [165]:
r_x = np.array(range(13), dtype=np.float)
r_y = np.array(range(13), dtype=np.float)
offset_x, offset_y = np.meshgrid(r_x, r_y)
# offset_x = offset_x[:, :, np.newaxis]
offset_x = np.repeat(offset_x[:, :, np.newaxis], 3, 2).flatten()[:, np.newaxis]
# offset_x = offset_x.flatten()[:, np.newaxis]
# offset_y = offset_y[:, :, np.newaxis]
# offset_y = np.repeat(offset_y, 3, 2)
# offset_y = offset_y.flatten()[:, np.newaxis]
offset_y = np.repeat(offset_y[:, :, np.newaxis], 3, 2).flatten()[:, np.newaxis]

offset_xy = np.concatenate((offset_x, offset_y), axis=1)

pprint(offset_xy.shape)
pprint(offset_xy[:20, :])

(507, 2)
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [3., 0.],
       [3., 0.],
       [3., 0.],
       [4., 0.],
       [4., 0.],
       [4., 0.],
       [5., 0.],
       [5., 0.],
       [5., 0.],
       [6., 0.],
       [6., 0.]])


In [163]:
a = torch.randn(2, 2, 85)
a[0, :, 44] = 100
inx = torch.argmax(a[:, :, 4:], dim=2)
clc, ind = torch.max(a[:, :, 4:], dim=2)
pprint(inx)
pprint(clc)

tensor([[40, 40],
        [44, 66]])
tensor([[100.0000, 100.0000],
        [  1.6155,   1.8283]])


In [5]:
import torch
import numpy as np 
from pprint import pprint

fsize = 19
w = torch.arange(fsize, dtype=torch.float).repeat(1, fsize, 1)
h = torch.arange(fsize, dtype=torch.float).repeat(1, fsize, 1).permute(0, 2, 1)
pprint(w)
pprint(h)

tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
          14., 15., 16., 17., 18.],
         [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12

In [13]:
a = torch.tensor([[1.2, 2.2]])
b = a.floor()
c = a.max(dim=1)
# print(a, b)
d = torch.tensor([1,2,3,4,5,6])
for i, di in enumerate(d):
    print(i, di)
# np.c_[:2]

0 tensor(1)
1 tensor(2)
2 tensor(3)
3 tensor(4)
4 tensor(5)
5 tensor(6)


In [56]:
import torch
import torch.nn as nn 
net = nn.Sequential(
    nn.Linear(1000, 500),
    nn.ReLU(),
    nn.Linear(500, 100),
    nn.ReLU(),
    nn.Linear(100, 4)
)

x = torch.randn((1, 1000))
y = torch.tensor([1])

In [57]:
pred = net(x)

print(pred.shape)

torch.Size([1, 4])


In [58]:
cred = nn.CrossEntropyLoss(reduction='sum')
loss = cred(y_hat, y)
print(loss)

tensor(1.1821)


In [59]:
y_f = torch.zeros((1, 4), dtype=torch.float)
y_f[0, 1] = 1
print(y_f)

tensor([[0., 1., 0., 0.]])


In [76]:
y = torch.tensor([1])
y_hat = torch.tensor([[0.12, 0.45, 0.21, 0.17]]).to(torch.float)
y_hat_l = torch.nn.functional.softmax(y_hat)

y_f = torch.zeros((1, 4), dtype=torch.float)
y_f[0, 1] = 1

print(torch.log(y_hat_l))

tensor([[-1.5121, -1.1821, -1.4221, -1.4621]])


In [84]:
cred_1 = torch.nn.functional.binary_cross_entropy(y_hat, y_f, reduction='sum')
print(cred_1)

cred_2 = nn.CrossEntropyLoss(reduction='sum')(y_hat, y)
print(cred_2)

cred_3 = nn.BCELoss(reduction='sum')(y_hat, y_f)
print(cred_3)


tensor(1.3484)
tensor(1.1821)
tensor(1.3484)


In [92]:
y_hat_log = torch.log(y_hat)
y_hat_mlog = torch.log(1-y_hat)

y_mf = (1 - y_f)
print(y_f)
print(y_mf)

tensor([[0., 1., 0., 0.]])
tensor([[1., 0., 1., 1.]])


In [94]:
loss = y_hat_log * y_f + y_hat_mlog * (1 - y_f)
print(loss.sum())

tensor(-1.3484)


In [3]:
import torch 
import numpy as np 

a = torch.tensor([[4,1], [5,6], [0, 0]])
b = torch.tensor([[2,6], [3,7]])
c = torch.nonzero(torch.sum(a, dim=-1), as_tuple=True)
# c = c.unsqueeze(-1)
d = torch.empty([])
print(d.shape)
print(d.device)

torch.Size([])
cpu


In [11]:
import numpy as np 

a = np.array([[1, 2], [0, 3]], dtype=np.float)
b = np.array([3, 4], dtype=np.float)

c = a + b / 2
print(np.pi)

3.141592653589793
